site_name: Scripts de Dani
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  logo: assets/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dcosimber/mkdocs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-costas-imbernón-512447b0

markdown_extensions: 
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: 
  Copyright © 2024 <a href="https://github.com/dcosimber" target="_blank" rel="noopener">Daniel Costas</a>



