site_url: https://dcosimber.github.io/bioinfo/
site_name: Dani Bioinfo
docs_dir: mk_docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  logo: assets/logo.png
extra_css:
    - stylesheets/custom.css
nav:
- Home: index.md
- Level 101:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: level101/linux_basics/intro.md

nav:
- Home: index.md
- Level 101:
    - Fundamentals Series:
        - Linux Basics:
            - Introduction: level101/linux_basics/intro.md
            - Command Line Basics: level101/linux_basics/command_line_basics.md
        - Linux Networking:
            - Introduction: level101/linux_networking/intro.md
            - HTTP: level101/linux_networking/http.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: 
  Copyright © 2024 <a href="https://github.com/dcosimber" target="_blank" rel="noopener">Daniel Costas</a>



